# Generated by Django 5.2.8 on 2025-11-27 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxelengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='voxelengine.documentationpage'),
        ),
    ]
